### ISSUE TITLE
plugins set bintrayOrganization to sbt

### ISSUE THREAD

**Issue by MasseGuillaume** [softprops/bintray-sbt#19]
https://github.com/softprops/bintray-sbt/blob/99260bc318744fb13008c97bee147f08c8741e24/src/main/scala/plugin.scala#L212

not shure why you set the org to sbt

**Comment by softprops** [comment]
`bintrayOrganization` should now default to your bintray credentials username. This is more inline with the sbt doc suggestions - http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html
