### ISSUE TITLE
bintrayPublishSettings vs bintraySettings

### ISSUE THREAD

**Issue by MasseGuillaume** [softprops/bintray-sbt#34]
`publish` with
`seq(bintrayPublishSettings:_*)` gives `java.lang.RuntimeException: Repository for publishing is not specified.`
but `seq(bintraySettings:_*)` works

**Comment by softprops** [comment]
closing. it shouldn't really matter anymore with the latest release http://notes.implicit.ly/post/118407794254/bintray-sbt-0-3-0 you shouldn't have to think to much about appending these settings lists any more
