### ISSUE TITLE
publish 0.2.0

### ISSUE THREAD

**Issue by softprops** [softprops/bintray-sbt#45]
todo:

- [x] complete release notes
- [x] update readme

**Comment by antonkulaga** [comment]
It will be great to see it, have you converted bintray to autoplugin already?

**Comment by softprops** [comment]
published [0.2.0](http://notes.implicit.ly/post/112460523949/bintray-sbt-0-2-0). I need to do some reading to figure out how autoplugin features can help make this plugin easier to integrate. Ill do that in a follow up.

**Comment by antonkulaga** [comment]
With autoplugin you can use autoimport feature to avoid adding ++bintrayKeys each time, for instance

**Comment by softprops** [comment]
I think you used to be able to do this by overriding settings on Plugins but it was discouraged. that may have changed since then though I guess

**Comment by softprops** [comment]
closing, just published 0.3.0 which is auto plugin friendly http://notes.implicit.ly/post/118407794254/bintray-sbt-0-3-0
