### ISSUE TITLE
stage/release for multi-project package support

### ISSUE THREAD

**Issue by eed3si9n** [softprops/bintray-sbt#52]
[1]: https://bintray.com/docs/usermanual/working/working_packages.html
  [2]: https://bintray.com/docs/usermanual/uploads/uploads_publishing.html
  [3]: https://github.com/xerial/sbt-sonatype#publishing-your-artifact

## many-to-many relationship between bintray package and subproject

sbt/sbt project is in the midst of exodus from Artifactory to Bintray.
What we would like to do is to create a single package named "sbt" that contains all the JARs from sbt/sbt. If I understand correctly, it's not possible do this with bintray-sbt for the following reasons:

1. currently bintray-sbt's notion of [bintray package][1] is tied one-on-one with sbt subproject.
2. as such, `publish` not only uploads the artifacts but also it [publishes the bintray version][2].

To disambiguate the term "publish", I'll use stage and release in the following definition:
- stage: upload artifacts such as JARs and Ivy files to a URL tied to a specific version of a bintray package. (In bintray lingo, this step called upload)
- release: finalize a specific version of a bintray package, and make the files available to public. (In bintray lingo, this step called publish)

Note: The separation between staging and releasing is somewhat analogous to that of Sonatype Nexus using [sbt-sonatype][3] where two tasks are called `publishSigned` and `sonatypeRelease`.

### bintrayPackge

First I would like to propose `bintrayPackge` setting to name the package for each subprojects. This could default to `moduleName` as the current implementation, but it would be something the build user can customize.

```scala
lazy val root = (project in file(".")).
  enablePlugins(bintrayPublishPlugin).
  settings(
    bintrayPackage := "sbt",
    ...
  )

lazy val app = project.
  enablePlugins(bintrayPublishPlugin).
  settings(
    bintrayPackage := "sbt"
  )

```

### publish + bintrayRelease combo

In this world, `publish` task only stages the JARs, but it won't actually release the version. Given that this changes the semantics from the current implementation of bintray-sbt, we could define a compatibility flag such as `bintrayReleaseOnPublish`:

```scala
bintrayReleaseOnPublish := false
```

and display some warning

```
> publish
[info] Packaging /Users/eugene/work/sbt-assembly/target/scala-2.10/sbt-0.13/sbt-assembly-0.13.1-889a0e33c79b9fd49cd43569f1e55dad430e59af.jar ...
[info] Done packaging.
[info] 	published sbt-assembly to com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.13.1-889a0e33c79b9fd49cd43569f1e55dad430e59af/jars/sbt-assembly.jar
....
[warn] You must run bintrayRelease task to release this version.
```

Once all subprojects are staged, you run `bintrayRelease` to release the version:

```
> bintrayRelease
[info] Version 0.13.1-889a0e33c79b9fd49cd43569f1e55dad430e59af is released.
```

**Comment by jsuereth** [comment]
This is a great writeup.  I'd also like to note that bintray-sbt ALSO supports sending artifacts to maven central, which is a *different* operation from "stage" or "release" in bintray.  Not sure we need to say anything else besides it's not the same as releasing, but also needs to exist in addtiion.

**Comment by jsuereth** [comment]
Also, I like the proposal

**Comment by jroper** [comment]
+1

We'd also like to use this in Play, we have several sbt plugins in our build, and it doesn't make sense that each one should be its own bintray package because they are all versioned together.  Plus, new plugins come and go, having to create new packages each time we add a new plugin is not something we want to do.

Another thing, the `bintrayRelease` task should also be responsible for uploading the version attributes, rather than modifying the `publish` task, that would solve issues like this one on the scala community build, where the `publishTo` is overridden:

https://github.com/sbt/sbt-web/pull/106

The bintray plugin should not cause builds that override `publishTo` to fail, for example, if you're building a local fork and deploying it to a private repository.

**Comment by jroper** [comment]
Oh, I see uploading the version attributes *is* the release step.  Anyway, not doing a `bintrayRelease` on `publish` would kill two birds with one stone, so +1.

**Comment by eed3si9n** [comment]
Actually uploading the file may or may not release the file on the spot - https://bintray.com/docs/api/#_upload_content

It's off by default, but bintray-sbt currently calls `publish(true)`, which is separate step from uploading the version attributes. I sent PR #53 if we want to discuss the code.

**Comment by softprops** [comment]
commented on the pull. I'm going to try and digest this.

> Note: The separation between staging and releasing is somewhat analogous to that of Sonatype Nexus using sbt-sonatype where two tasks are called publishSigned and sonatypeRelease.

My hope is that doesn't add friction to the publishing process. What I never liked about nexus was how complicated it was to publish something. I kind of like the simplicity of `sbt> publish` as the entire flow for publishing.

I can understand though that it takes a run to realize that you've made a mistake if you've misconfigured your build to publish projects ( or not publish projects ) and this is annoying with one command. "Go home, you're drunk" is a bad user experience. So maybe this is a good addition. I have to double check but the only thing that has bitten my is the publishing of the default implicit aggregator project which has no artifacts of its own 99% of the time.

That said. I'd want `bintrayReleaseOnPublish := false` to set to true by default, is possible to remove any complexity for publishing simple projects. Most of my projects are simple projects on purpose!

> This is a great writeup. I'd also like to note that bintray-sbt ALSO supports sending artifacts to maven central, which is a different operation from "stage" or "release" in bintray. Not sure we need to say anything else besides it's not the same as releasing, but also needs to exist in addtiion.

There's a sync task for this I think it has a dependency on your version be published ( and linked to jcenter ), ( and meeting all of sonatypes pom, pgp requirements ) :)

> Another thing, the bintrayRelease task should also be responsible for uploading the version attributes, rather than modifying the publish task, that would solve issues like this one on the scala community build, where the publishTo is overridden:

I've been meaning to make this its own task, syncing updating, removing version attrs and/or package attrs ( in bintray terms )

**Comment by eed3si9n** [comment]
> My hope is that doesn't add friction to the publishing process. What I never liked about nexus was how complicated it was to publish something. I kind of like the simplicity of sbt> publish as the entire flow for publishing.
> 
> [snip] 
>
> That said. I'd want `bintrayReleaseOnPublish := false` to set to true by default, is possible to remove any complexity for publishing simple projects. 

I would like to understand what the tradeoffs are here. One of the motivation for the separation of staging/releasing is that without it, it can't do certain things.

@jsuereth: Is it mostly about keeping things hidden before all the bits are in place?

I read somewhere that if you sync _2.10 to Maven Central but forgot to publish _2.11 you can't sync later. Not sure if that scenario is just limitation of bintray, or it can be prevented by having staging.

**Comment by jsuereth** [comment]
there's two things here:

1. if someone does "set publishTo" overriding publish will mean we explode at runtime.  This breaks dbuild + the community build if we use bintray-sbt today, which is why we've avoided it until now.
2. The sync thing matters.  It's posisble one project is released without another being released, which is really bad.

Just having release happen later solves this issue, as you shouldn't have to check credentials in publish, and you aren't hijacking publish so the community build can work.

**Comment by softprops** [comment]
I'm not against the change, just the default of opting in.

> I would like to understand what the tradeoffs are here.

The term publish no longer means *publish*.

> I read somewhere that if you sync _2.10 to Maven Central but forgot to publish _2.11 you can't sync later. Not sure if that scenario is just limitation of bintray, or it can be prevented by having staging.

There is a limit of not being able to update a given version's contents after 180 days. If a new version of scala comes out and you decide to cross publish after that time you could be forced to create a new bintray package version.

**Comment by eed3si9n** [comment]
> The term publish no longer means publish.

From my point of view, sbt's `publish` task aligns closer with bintray's "upload" concept. Similar to Sonatype Nexus's workflow, bintray also employs the two-phase stage + release process on their web UI.

> There is a limit of not being able to update a given version's contents after 180 days. If a new version of scala comes out and you decide to cross publish after that time you could be forced to create a new bintray package version.

ok. so that means there's nothing in releasing (or staging) that's going to harm the syncing? If that's the case, I think you get to call the shot on the default value.
