### ISSUE TITLE
Unable to run bintray::publish.

### ISSUE THREAD

**Issue by alexflav23** [softprops/bintray-sbt#54]
```
Error: was not able to find or create a package for companyname in maven named 

```

My settings look like this:

```scala
   val publishSettings: Seq[Def.Setting[_]] = Seq(
    publishMavenStyle := true,
    publishArtifact in Test := false,
    pomIncludeRepository := { _ => true},
    bintray.Keys.bintrayOrganization in bintray.Keys.bintray := Some("mycomp"),
    licenses += ("Apache-2.0", url("https://www.apache.org/licenses/LICENSE-2.0"))
)
```

In bintray, I even created the packages manually under maven, to exactly match what I'm trying to publish, but the error won't go away. Could you please suggest any possible fixes?

**Comment by softprops** [comment]
is your build on github where I can take a look?

**Comment by alexflav23** [comment]
Hi @softprops,

Thank you for getting back to me. It's here [here](https://github.com/websudos/lift-shiro/blob/master/project/build.scala)

Regards,

**Comment by alexflav23** [comment]
@softprops All figured out, I was using my email instead of username in credentials. Long story short, everything works now.

**Comment by softprops** [comment]
awesome. I'll enjoy a few extra hours this weekend :) have a good one
