### ISSUE TITLE
Where is 0.3.0?

### ISSUE THREAD

**Issue by schmmd** [softprops/bintray-sbt#55]
It's not at https://dl.bintray.com/sbt/sbt-plugin-releases/me.lessis/bintray-sbt/scala_2.10/sbt_0.13/.

**Comment by softprops** [comment]
sry it's unreleased as of yet. I just merged in pr which updated the readme. I'll try to publish that soon. In the mean time I'd recommend 0.2.1

**Comment by alexflav23** [comment]
@softprops Any news on 0.3.0?

**Comment by benmccann** [comment]
It's super super confusing that the README refers to a version that doesn't exist

**Comment by softprops** [comment]
I'll try to get this done tomorrow evening. The Readme changes came with in with a recent pull.

**Comment by metasim** [comment]
Might want to change the README until 0.3.0 is release...

**Comment by softprops** [comment]
should be good to go. here's the highlight reel -- http://notes.implicit.ly/post/118407794254/bintray-sbt-0-3-0
