### ISSUE TITLE
{"message":"Package 'dadagen' was not found"}

### ISSUE THREAD

**Issue by rbuckland** [softprops/bintray-sbt#58]
When Uploading for the first time to bintray, I am getting an error stating that the package was not found.

From the documentation I can see that bintray-sbt is meant to create a new package for me// but alas I get this error
```
[error] (*:publish) error uploading to https://api.bintray.com/maven/inosion/maven/maven/org/inosion/dadagen/dadagen_2.11/0.2.6/dadagen_2.11-0.2.6-tests-javadoc.jar: {"message":"Package 'dadagen' was not found"}
```
Currently the project https://github.com/inosion/dadagen has only one artifact, but I will soon be moving it to a multi project.

I am attempting to push the library up into the Inosion Organisation on Bintray.

**Comment by softprops** [comment]
This is probably a regression introduced in the latest release. I'll have a look this weekend

**Comment by jodersky** [comment]
Same problem. Furthermore, I'm using sbt-pgp for signed publishing and noticed that `publishSigned ` always fails whereas `publish` has around 50% chance of succeeding.

**Comment by bryce-anderson** [comment]
When will a version of bintray-sbt be released with this fix?
