### ISSUE TITLE
Incorrect developers section in generated POM

### ISSUE THREAD

**Issue by pathikrit** [softprops/bintray-sbt#75]
If you have this line in your `build.sbt`:

```scala
developers := List(
  Developer("pathikrit", "Pathikrit Bhowmick", "pathikritbhowmick@msn.com", url("https://github.com/pathikrit"))
)
```

It generates this POM:
```xml
    <developers> moduleInfo.developers.map&lt;function1&gt; </developers>
```

I guess its doing a toString on the map ??

**Comment by softprops** [comment]
This plugin doesn't do any artifact generation itself. Sbt does that.  You may wish to open this issue there
